# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bbctl < Formula
  desc "Gated EC2 access for Blackbuck — auditable, approval-driven, immutable logs"
  homepage "https://github.com/Blackbuck-LABS/bbctl"
  version "0.5.8"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Blackbuck-LABS/bbctl/releases/download/v0.5.8/bbctl_0.5.8_darwin_x86_64.tar.gz"
      sha256 "c1870570fec9aaf9e45312cecd92058ce3e6dc9a4635e665331a8f712dc54272"

      define_method(:install) do
        bin.install "bbctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Blackbuck-LABS/bbctl/releases/download/v0.5.8/bbctl_0.5.8_darwin_arm64.tar.gz"
      sha256 "dd0a4f46535c873b4cecfd8f100a7657d6c9f77025baa7bfa2c7f65cbbf85d32"

      define_method(:install) do
        bin.install "bbctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Blackbuck-LABS/bbctl/releases/download/v0.5.8/bbctl_0.5.8_linux_x86_64.tar.gz"
      sha256 "d42cff5457def66f8bdc984c97f93de10242c60db64dd68133ac326770c28fb1"
      define_method(:install) do
        bin.install "bbctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Blackbuck-LABS/bbctl/releases/download/v0.5.8/bbctl_0.5.8_linux_arm64.tar.gz"
      sha256 "fd642b62870ce456ad4391dc24763fefb917738c884949bdb380f9d171bf30ba"
      define_method(:install) do
        bin.install "bbctl"
      end
    end
  end

  test do
    system "#{bin}/bbctl", "version"
  end
end
