# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bbctl < Formula
  desc "Gated EC2 access for Blackbuck — auditable, approval-driven, immutable logs"
  homepage "https://github.com/Blackbuck-LABS/bbctl"
  version "1.4.0"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Blackbuck-LABS/bbctl/releases/download/v1.4.0/bbctl_1.4.0_darwin_x86_64.tar.gz"
      sha256 "bcd45177aad84d5f8cdbcae559a0bfd24490a0c34e183ee60ac8eca3b27fd128"

      define_method(:install) do
        bin.install "bbctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Blackbuck-LABS/bbctl/releases/download/v1.4.0/bbctl_1.4.0_darwin_arm64.tar.gz"
      sha256 "68e2b00d23ab503ce97691e9c1916624ba434f382e7b46751c8a8d3603487940"

      define_method(:install) do
        bin.install "bbctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Blackbuck-LABS/bbctl/releases/download/v1.4.0/bbctl_1.4.0_linux_x86_64.tar.gz"
      sha256 "d14dbd79dfb3d124069f6f91b31bfbeda71af2e6b1aecd3a03d9c4322f1cc025"
      define_method(:install) do
        bin.install "bbctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Blackbuck-LABS/bbctl/releases/download/v1.4.0/bbctl_1.4.0_linux_arm64.tar.gz"
      sha256 "0efb111349ac4ca8e6e55f259578e52ccb38fce1c7bb08ec17c53e9a9dcd12be"
      define_method(:install) do
        bin.install "bbctl"
      end
    end
  end

  test do
    system "#{bin}/bbctl", "version"
  end
end
